export const ELEMENTS = {
  URL: "https://europa.eu/europass/eportfolio/screen/profile?lang=en",
  LOGIN: "#loginHere > .ux-u-cursor-pointer",
  USERNAME: "input#username",
  USER: "luisnt@gmail.com",
  BTN_NEXT: ".text-right > .btn",
  PASSWORD: "input#password",
  PASS: "",
  BTN_ENTRAR: ".btn",
  BTN_COOKIES: ".wt-cck-btn-add",
  BTN_PROFILE: ".wrapper-center > .btn",
  BTN_EDIT_SKILLS:
    ".mt-4 > .action-buttons > div.ng-star-inserted > eprofile-edit-delete-buttons > .edit-delete-buttons > .edit-button > .btn",
  INPUT_SKILL:
    "input.ng-tns-c48-2.ui-inputtext.ui-widget.ui-state-default.ui-corner-all.ui-autocomplete-input.ng-star-inserted",
  BTN_ADD_SKILL: ".input-group-append > .btn",
  BTN_SAVE: ".save-personal-info-btn > .btn",
  SKILLS: [
    "AdonisJS 1-2 anos",
    "Api 5+ anos",
    "Batchfile 5+ anos",
    "Bootstrap 5+ anos",
    "Clean Code 1-2 anos",
    "Cordova 1-2 anos",
    "CSS 5+ anos",
    "CSV 5+ anos",
    "Delphi 5+ anos",
    "Design Pattern 2-3 anos",
    "Docker 2-3 anos",
    "Dockerfile 2-3 anos",
    "ES6 5+ anos",
    "Excel 5+ anos",
    "Express 5+ anos",
    "Figma 1-2 anos",
    "GraphQL 0-1 anos",
    "Heroku 5+ anos",
    "HTML 5+ anos",
    "HTTP 5+ anos",
    "IDL 5+ anos",
    "INI 5+ anos",
    "Inno Setup 5+ anos",
    "Ionic 2-3 anos",
    "JavaScript 5+ anos",
    "jQuery 5+ anos",
    "JSON 5+ anos",
    "JSX 5+ anos",
    "Jupyter Notebook 0-1 anos",
    "kubernetes 2-3 anos",
    "Laravel 4-5 anos",
    "Linux 5+ anos",
    "MariaDB 5+ anos",
    "Markdown 5+ anos",
    "MongoDB 2-3 anos",
    "MVC 5+ anos",
    "MVVM 5+ anos",
    "MySQL 5+ anos",
    "NextJS 4-5 anos",
    "Node.js 5+ anos",
    "NoSQL 2-3 anos",
    "NPM 5+ anos",
    "ORACLE 5+ anos",
    "Pandas 0-1 anos",
    "Pascal 5+ anos",
    "Perl 0-1 anos",
    "PhoneGap 1-2 anos",
    "Photoshop 2-3 anos",
    "PHP 5+ anos",
    "PLpgSQL 5+ anos",
    "PLSQL 5+ anos",
    "Pod 2-3 anos",
    "POO 5+ anos",
    "PostgreSQL",
    "PowerShell 0-1 anos",
    "PWA 2-3 anos",
    "Python 0-1 anos",
    "ReactJS 5+ anos",
    "RESTful 5+ anos",
    "S.O.L.I.D 5+ anos",
    "Sass 2-3 anos",
    "SCSS 2-3 anos",
    "Shell Script 2-3 anos",
    "Spring Boot 0-1 anos",
    "SQL 5+ anos",
    "SQL Server 5+ anos",
    "SQLite 5+ anos",
    "SQLPL 5+ anos",
    "SVG 0-1 anos",
    "TypeScript 2-3 anos",
    "VCL 5+ anos",
    "Vue.js 1-2 anos",
    "Web API 5+ anos",
    "Web Services 5+ anos",
  ],
}
